{{- if eq .Values.deployment.ingress.enabled true -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ui.deployment.ingress.fullname" . }}
  labels:
    app: {{ template "ui.name" . }}
    chart: {{ template "ui.chart" . }}
    component: {{ .Values.deployment.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.deployment.ingress.annotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.deployment.ingress.tls }}
  tls:
  {{- range .Values.deployment.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.deployment.ingress.hostname }}
      http:
        paths:
          - pathType: Prefix
          {{- if index $.Values.deployment.ingress "annotations" }}
          {{- if eq (index $.Values.deployment.ingress.annotations "kubernetes.io/ingress.class" | default "") "gce" "alb" "nsx" }}
            path: /*
          {{- else }}{{/* Has annotations but ingress class is not "gce" nor "alb" */}}
            path: /
          {{- end }}
          {{- else}}{{/* Has no annotations */}}
            path: /
          {{- end }}
            backend:
              service:
                name: {{ template "ui.deployment.service.fullname" . }}
                port:
                  number: {{ .Values.deployment.service.http_port }}
{{- end }}