apiVersion: v1
kind: Service
metadata:
  name: {{ template "ui.deployment.service.fullname" . }}
  labels:
    app: {{ template "ui.name" . }}
    chart: {{ template "ui.chart" . }}
    component: {{ .Values.deployment.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    monitor: {{ .Values.deployment.monitorLabel }}
spec:
  type: {{ .Values.deployment.service.type }}
  ports:
  - port: {{ .Values.deployment.service.http_port }}
    targetPort: {{ .Values.deployment.service.targetPort }}
    {{- if .Values.deployment.service.nodePort }}
    nodePort: {{ .Values.deployment.service.nodePort }}
    {{- end }}
    name: {{ .Values.deployment.service.name | default "ui-http" }}
  selector:
    app: {{ template "ui.name" . }}
    chart: {{ template "ui.chart" . }}
    component: {{ .Values.deployment.name }}
    release: {{ .Release.Name }}
