apiVersion: v2
name: air
description: A Helm chart for Project Air
type: application
version: 0.2.0
appVersion: 0.6.0

dependencies:
  - name: ingress-nginx
    version: 4.0.6
    repository: https://kubernetes.github.io/ingress-nginx 
  - name: air-ui-oss
    version: 0.1.0
    repository: "file://../air-ui-oss"
    condition: air-ui-oss.enabled 
  - name: mosquitto
    version: 2.3.0
    repository: https://storage.googleapis.com/t3n-helm-charts
    condition: mosquitto.enabled 
  - name: dgraph
    version: 0.0.18
    repository: "file://../dgraph"
    condition: dgraph.enabled
  - name: dgraph-loader
    version: 0.0.1
    repository: "file://../dgraph-loader"
  - name: air-data-mqtt-dgraph
    version: 0.1.0
    repository: "file://../air-data-mqtt-dgraph"
  - name: air-metadata-mqtt-dgraph
    version: 0.1.0
    repository: "file://../air-metadata-mqtt-dgraph" 
  - name: air-notification-mqtt-dgraph
    version: 0.1.0
    repository: "file://../air-notification-mqtt-dgraph"