apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "dgraphloader.liveloader.job.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: live-loader-job
        image: {{ template "dgraphloader.image" . }}
        command: ['sh', '-c', 'base64 -d /etc/loader/schema_data.rdf > schema_data.rdf && base64 -d /etc/loader/seed_data.rdf > seed_data.rdf && dgraph live -f seed_data.rdf -s schema_data.rdf -a {{ template "dgraph.alpha.fullname" . }}:9080 -z  {{ template "dgraph.zero.fullname" . }}:5080']
        volumeMounts:
        - name: loader-volume
          mountPath: /etc/loader
      volumes:
        - name: loader-volume
          configMap:
            name: {{ template "dgraphloader.liveloader.configmap.fullname" . }}